import Head from 'next/head'
import Header from '@/components/header'
import Footer from '@/components/footer'
import ServiceGrid from '@/components/service-grid'
import PortfolioGrid from '@/components/tab-three'

export default function Home() {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        <Header color="color-black" />
        {/* Start Slider Area   */}
        <div className="prv-banner-wrapper"
          style={{ backgroundImage: 'url(images/preview-bg.jpg)' }}>
          <div className="container-fluid">
            <div className="plr--120">
              <div className="row">
                <div className="col-lg-8 col-xl-5">
                  <div className="inner">
                    <div className="logo text-left">
                      <img src="icons/logo.png" alt="BigBee" />
                      <span style={{ fontSize: '1.6em', marginLeft: '10px' }}>BigBee</span>
                    </div>
                    <p className="title">Embrace your moments</p>
                    <div className="contact-btn">
                      <a href="https://themeforest.net/checkout/from_item/25457315?license=regular" target="_blank" className="rn-button-style--2 btn-solid">Contact US</a>
                    </div>
                  </div>
                </div>
              </div>
            </div>
          </div>
        </div>
        <div id='home' className="fullscreen empty-div gradient-overlay"></div>
        {/* End Slider Area   */}

        {/* Start Portfolio  */}
        <div id="portfolio" className="designer-portfolio-area ptb--120 bg_color--1">
          <PortfolioGrid column="col-lg-4 col-md-6 col-sm-6 col-12" />
        </div>
        {/* End Portfolio  */}

        {/* Our service */}
        <div id="service" className="fix">
          <div className="service-area creative-service-wrapper ptb--120 bg_color--5" >
            <div className="container">
              <div className="row">
                <div className="col-lg-12">
                  <div className="section-title text-center service-style--3 mb--30 mb_sm--0">
                    <h2 className="title">Our Service</h2>
                    <p>There are many variations of passages of Lorem Ipsum available, but the majority have suffered alteration.</p>
                  </div>
                </div>
              </div>
              <div className="row creative-service">
                <div className="col-lg-12">
                  <ServiceGrid className='col-lg-4 col-md-6 col-sm-6 col-12 text-left' />
                </div>
              </div>
            </div>
          </div>
        </div>
        {/* End our service */}

        <Footer />
        <div id='contact' />
      </main>
    </>
  )
}
